[theme]
primaryColor = "#1DB954" # Spotify Green
backgroundColor = "#191414" # Spotify Black
secondaryBackgroundColor = "#212121"
textColor = "#FFFFFF"
font = "sans serif"

[server]
port = 8501
headless = true